# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7615413422db487dd085c725819ad2b2b7b032f4243d4518db7e47bcf51de714892960eaf95caac82cf47b50f2bd168b50050107ddf7080bf0646510bd3c2f25

test:
  secret_key_base: 567247ab94a41d827db13c26805352fb175e69627881e6b346a4bfe33d7d851a6fddaabc99a5391bff7712198411342f666a7b498059f2a4f81dae5fa522ebf5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
